name: Auto Result Sync

on:
  schedule:
    # Every 15 minutes from 11:00 AM to 10:45 PM IST
    - cron: "*/15 5-17 * * *"

  workflow_dispatch:
    inputs:
      draw:
        description: "Select Draw"
        required: true
        default: "AUTO"
        type: choice
        options:
          - AUTO
          - 1PM
          - 6PM
          - 8PM

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      TZ: Asia/Kolkata
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Result Sync
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FORCE_DRAW: ${{ github.event.inputs.draw || 'AUTO' }}
        run: |
          echo "DRAW SELECTED = $FORCE_DRAW"
          python -m py_compile backend/sync_results.py
          python -u backend/sync_results.py
